# Generated by Django 3.1 on 2023-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='course',
            field=models.ManyToManyField(to='WTdegreecheck.Course'),
        ),
    ]
