# Generated by Django 4.2 on 2023-11-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WTdegreecheck.department')),
            ],
        ),
    ]
