# Generated by Django 3.1 on 2023-10-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0002_major_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
