# Generated by Django 4.2 on 2023-11-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0003_faculty_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adviser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WTdegreecheck.faculty'),
        ),
    ]
