# Generated by Django 3.1 on 2023-10-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0004_auto_20231008_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='core',
            field=models.ManyToManyField(related_name='majors', to='WTdegreecheck.Core'),
        ),
    ]
