# Generated by Django 4.2 on 2023-11-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0004_student_adviser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrade',
            old_name='major',
            new_name='course',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WTdegreecheck.semester'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='yeartaken',
            field=models.IntegerField(default=1, help_text='program year'),
            preserve_default=False,
        ),
    ]
