# Generated by Django 3.1 on 2023-10-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0005_auto_20231008_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='core',
        ),
        migrations.AddField(
            model_name='major',
            name='cores',
            field=models.ManyToManyField(to='WTdegreecheck.Core'),
        ),
    ]
