# Generated by Django 4.2 on 2023-12-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0005_rename_major_studentgrade_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
