# Generated by Django 4.2.6 on 2023-10-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0007_rename_cores_major_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_core', models.BooleanField()),
                ('is_degree', models.BooleanField()),
                ('is_major', models.BooleanField()),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WTdegreecheck.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='degreecheck',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='degreecheck',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='coursestaken',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='major',
            name='core',
        ),
        migrations.RemoveField(
            model_name='major',
            name='course_req',
        ),
        migrations.DeleteModel(
            name='Core',
        ),
        migrations.DeleteModel(
            name='Coursetype',
        ),
        migrations.DeleteModel(
            name='Degreecheck',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='major_course',
            name='major',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WTdegreecheck.major'),
        ),
        migrations.AddField(
            model_name='major_course',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WTdegreecheck.semester'),
        ),
    ]
