# Generated by Django 4.2.6 on 2023-10-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0008_major_course_remove_degreecheck_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='major_course',
            name='year',
            field=models.IntegerField(default=0, help_text='program year'),
            preserve_default=False,
        ),
    ]
