# Generated by Django 4.2 on 2023-11-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0009_major_course_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Major_course',
            new_name='Majorcourse',
        ),
    ]
