# Generated by Django 4.2.6 on 2023-12-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WTdegreecheck', '0011_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(help_text='ex: aa1234567', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WTdegreecheck.course'),
        ),
    ]
